runtime: java
env: flex
runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
handlers:
  - url: /.*
    script: this field is required, but ignored
automatic_scaling:
  max_num_instances: 1
beta_settings:
  cloud_sql_instances: ambrosia-259011:us-central1:ambrosia-db
