substitutions:
  _IMAGE_NAME: docker-ambrosia
  _GCS_CACHE_BUCKET: cloud-build-m2-cache

steps:

  # load the cache from GCS if it exists
  - name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        (
          gsutil cp gs://${PROJECT_ID}-${_GCS_CACHE_BUCKET}/m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
          tar -xzf /tmp/m2-cache.tar.gz
        ) || echo 'Cache not found'
    volumes:
      - name: m2
        path: /root/.m2/


  - name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
    id: build
    entrypoint: bash
    args: ['-c',
           'mvn clean install -Dmaven.test.skip=true jib:build -Dimage=gcr.io/${PROJECT_ID}/${_IMAGE_NAME} -Ddb.url=$$DB_URL -Ddb.user=$$DB_USER -Ddb.user.pw=$$DB_USER_PW -Dpw.salt.one=$$PW_SALT_ONE -Dpw.salt.two=$$PW_SALT_TWO -Djwt.secret=$$JWT_SECRET']
    secretEnv: ['DB_URL', 'DB_USER', 'DB_USER_PW', 'PW_SALT_ONE', 'PW_SALT_TWO', 'JWT_SECRET']
    volumes:
      - name: m2
        path: /root/.m2/

  # cache the /root/.m2 folder and upload it to GCS bucket
  - name: gcr.io/cloud-builders/gsutil
    waitFor:
      - build
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        tar -czf /tmp/m2-cache.tar.gz .m2 &&
        gsutil cp /tmp/m2-cache.tar.gz gs://${PROJECT_ID}-${_GCS_CACHE_BUCKET}/m2-cache.tar.gz
    volumes:
      - name: m2
        path: /root/.m2/

  # Deploy to GAE
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor:
      - build
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--promote'
      - '--stop-previous-version'
      - '--image-url'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

timeout: 900s

secrets:
  - kmsKeyName: projects/ambrosia-259011/locations/global/keyRings/ambrosia-prod/cryptoKeys/secret
    secretEnv:
      DB_URL: CiQAew1wY9RxAYxhA9Hc2LATgCBew1WBX59sThiYNYoGOJtjOeISWACq0ITPflIOzC2/VZP5HNXa0rz7PdzuK379Us8z4Yp5tcx0Ctum4B5dEYCkTInvTHe1yDu5ogDplUIRk6KXl74NyZc0fraDAhlQmUMG1jG3uRWnr6nbIms=
      DB_USER: CiQAew1wY36MAyOFSaY9Kg6pgHv+mCJ3p0JOFYv6suRiey64XroSNgCq0ITPHckE600ACZv6pI/0VKoDUK3Z5WsFEsL8fXS5tH8zLnfshPwJiwyWpo/OfnnsiFmi1Q==
      DB_USER_PW: CiQAew1wY3+shVbI6xked/Ph097YGHym/piYxn2wEkJ0kWxW/fYSPQCq0ITP3yTIQM8NdqDSE9yq6nKw8OE3eKnaVYDjoa7klK9zvlY+GAYA6ICdsVYabPwAT7BJqSYOgVOFVIs=
      PW_SALT_ONE: CiQAew1wY1m7QlvQsyn3m5kZTIq2TFF5C7EtZ2sx1wX+1Wx0Z8ISPQCq0ITPBKlP6v8CJAZ6pmLV4l042DHq1bJmMDio/P4zxMHvXdhAnerhURpF4DXZyZI6O1AE1K3g49BA1JQ=
      PW_SALT_TWO: CiQAew1wY5h9Lynbj8K3SykAx9UIGJOMOtY/VXp6fwY8BFD8hPwSPACq0ITPzMLuj5OZSVUEU0OFIgC+6gEQ53r6xX8tIAeTO9XwMkEHTfMLoGi2cYFm7xAXvgjsRF4+s2ja/g==
      JWT_SECRET: CiQAew1wY8cwEKQ9wj4wKKmtEimoAafwOmN0xRpIBjVwWRNjTFcSSgCq0ITP6lIgkTpcF1LlJTs7klR+UqQMkjRYMl+29/lqSyDuC0tYv5cydUG7jQ3Nlkb0tAbUauK9nzIeWbKhXNOHOuSOkZ46BCFd
