package io.pacworx.ambrosia.resources

import com.fasterxml.jackson.annotation.JsonFormat
import io.pacworx.ambrosia.resources.ResourceTypeCategory.*

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
enum class ResourceType(val category: ResourceTypeCategory) {
    STEAM(TIME_GENERATED), STEAM_MAX(DEFINITION), PREMIUM_STEAM(CONSUMABLE), PREMIUM_STEAM_MAX(DEFINITION),
    COGWHEELS(TIME_GENERATED), COGWHEELS_MAX(DEFINITION), PREMIUM_COGWHEELS(CONSUMABLE), PREMIUM_COGWHEELS_MAX(DEFINITION),
    TOKENS(TIME_GENERATED), TOKENS_MAX(DEFINITION), PREMIUM_TOKENS(CONSUMABLE), PREMIUM_TOKENS_MAX(DEFINITION),
    COINS(UNLIMITED), RUBIES(UNLIMITED),
    METAL(CONSUMABLE), METAL_MAX(DEFINITION), IRON(CONSUMABLE), IRON_MAX(DEFINITION), STEAL(CONSUMABLE), STEAL_MAX(DEFINITION),
    WOOD(CONSUMABLE), WOOD_MAX(DEFINITION), BROWN_COAL(CONSUMABLE), BROWN_COAL_MAX(DEFINITION), BLACK_COAL(CONSUMABLE), BLACK_COAL_MAX(DEFINITION),
    SIMPLE_GENOME(UNLIMITED), COMMON_GENOME(UNLIMITED), UNCOMMON_GENOME(UNLIMITED), RARE_GENOME(UNLIMITED), EPIC_GENOME(UNLIMITED)
    ;

    fun getName(): String = name
}