spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

ambrosia:
  pw-salt-one: ${PW_SALT_ONE}
  pw-salt-two: ${PW_SALT_TWO}
  jwt-secret: ${JWT_SECRET}
