

spring:
    application:
      name: ambrosia-api
    datasource:
        driver-class-name: org.postgresql.Driver
    jackson:
        serialization.write_dates_as_timestamps: false
        mapper.default-view-inclusion: true
    jpa:
      show-sql: false
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
    profiles:
      active: local

springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger.html

ambrosia:
  pw-salt-one: cslqwooiqz
  pw-salt-two: ier23caop1
  jwt-secret: qwpocani23j89dfwjjocwimnjn49
