package io.pacworx.ambrosia.maps

enum class MapTileType {
    NONE, ASH, DESERT, SAND, RED_SAND, GREEN_SAND, MUD, ROCK, BROWN_ROCK, RED_ROCK, GREEN_STONE,
    GRASS, MOSS, FOREST,
    SNOWCOVERED_GRASS, SNOW, SNOW_MUD, LAVA, MAGMA, WATER
}