create table dynamic_property (
  id bigserial,
  category varchar(32) not null,
  type varchar(32) not null,
  level int,
  stat varchar(32),
  value1 int not null,
  value2 int,
  primary key (id)
);

insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 1, null, 750);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 2, null, 800);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 3, null, 900);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 4, null, 1020);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 5, null, 1200);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 6, null, 1470);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 7, null, 1630);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 8, null, 1875);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 9, null, 2100);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 10, null, 2500);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 11, null, 3500);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 12, null, 3720);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 13, null, 3930);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 14, null, 4360);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 15, null, 4820);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 16, null, 5190);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 17, null, 5620);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 18, null, 6100);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 19, null, 6750);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 20, null, 7500);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 21, null, 9000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 22, null, 9900);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 23, null, 11110);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 24, null, 12320);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 25, null, 13100);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 26, null, 15600);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 27, null, 16740);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 28, null, 17720);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 29, null, 18810);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 30, null, 20000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 31, null, 24000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 32, null, 25300);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 33, null, 26850);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 34, null, 28130);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 35, null, 30620);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 36, null, 31850);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 37, null, 33240);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 38, null, 34990);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 39, null, 36360);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 40, null, 38000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 41, null, 43000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 42, null, 44700);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 43, null, 46590);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 44, null, 48650);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 45, null, 50270);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 46, null, 52310);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 47, null, 54850);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 48, null, 57500);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 50, null, 60000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 51, null, 67000);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 52, null, 69820);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 53, null, 72860);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 54, null, 75890);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 55, null, 80920);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 56, null, 86980);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 57, null, 92550);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 58, null, 97830);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 59, null, 104500);
insert into dynamic_property values (default, 'HERO', 'XP_MAX_HERO', 60, null, 110000);

insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 0, null, 2000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 1, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 2, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 3, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 4, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 5, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 6, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 7, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 8, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 9, null, 10000);
insert into dynamic_property values (default, 'HERO', 'ASC_POINTS_MAX_HERO', 10, null, 10000);

insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 1, null, 125);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 2, null, 155);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 3, null, 215);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 4, null, 267);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 5, null, 300);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 6, null, 345);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 7, null, 388);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 8, null, 431);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 9, null, 500);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 10, null, 566);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 11, null, 622);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 12, null, 712);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 13, null, 830);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 14, null, 960);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 15, null, 1050);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 16, null, 1230);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 17, null, 1520);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 18, null, 1935);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 19, null, 2245);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 20, null, 2690);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 21, null, 3185);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 22, null, 3870);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 23, null, 4730);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 24, null, 5690);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 25, null, 6360);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 26, null, 7130);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 27, null, 7980);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 28, null, 9240);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 29, null, 10490);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 30, null, 12470);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 31, null, 15100);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 32, null, 18100);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 33, null, 22480);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 34, null, 26870);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 35, null, 29810);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 36, null, 33500);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 37, null, 38920);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 38, null, 44820);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 39, null, 49530);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 40, null, 55340);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 41, null, 63490);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 42, null, 70630);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 43, null, 78430);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 44, null, 85880);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 45, null, 95890);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 46, null, 102740);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 47, null, 110460);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 48, null, 120210);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 49, null, 131030);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 50, null, 143060);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 51, null, 155970);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 52, null, 168120);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 53, null, 180830);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 54, null, 195830);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 55, null, 217420);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 56, null, 235810);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 57, null, 260470);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 58, null, 288900);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 59, null, 310410);
insert into dynamic_property values (default, 'HERO', 'MERGE_XP_HERO', 60, null, 358900);

insert into dynamic_property values (default, 'GEAR', 'HP_ABS_GEAR', 1, null, 10, 25);
insert into dynamic_property values (default, 'GEAR', 'HP_ABS_GEAR', 2, null, 20, 45);
insert into dynamic_property values (default, 'GEAR', 'HP_ABS_GEAR', 3, null, 40, 85);
insert into dynamic_property values (default, 'GEAR', 'HP_ABS_GEAR', 4, null, 75, 125);
insert into dynamic_property values (default, 'GEAR', 'HP_ABS_GEAR', 5, null, 115, 190);
insert into dynamic_property values (default, 'GEAR', 'HP_ABS_GEAR', 6, null, 175, 250);
insert into dynamic_property values (default, 'GEAR', 'HP_PERC_GEAR', 1, null, 5, 8);
insert into dynamic_property values (default, 'GEAR', 'HP_PERC_GEAR', 2, null, 7, 15);
insert into dynamic_property values (default, 'GEAR', 'HP_PERC_GEAR', 3, null, 13, 28);
insert into dynamic_property values (default, 'GEAR', 'HP_PERC_GEAR', 4, null, 23, 43);
insert into dynamic_property values (default, 'GEAR', 'HP_PERC_GEAR', 5, null, 32, 65);
insert into dynamic_property values (default, 'GEAR', 'HP_PERC_GEAR', 6, null, 53, 84);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_ABS_GEAR', 1, null, 10, 25);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_ABS_GEAR', 2, null, 20, 45);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_ABS_GEAR', 3, null, 40, 85);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_ABS_GEAR', 4, null, 75, 125);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_ABS_GEAR', 5, null, 115, 190);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_ABS_GEAR', 6, null, 175, 250);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_PERC_GEAR', 1, null, 5, 8);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_PERC_GEAR', 2, null, 7, 15);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_PERC_GEAR', 3, null, 13, 28);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_PERC_GEAR', 4, null, 23, 43);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_PERC_GEAR', 5, null, 32, 65);
insert into dynamic_property values (default, 'GEAR', 'ARMOR_PERC_GEAR', 6, null, 53, 84);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_ABS_GEAR', 1, null, 10, 25);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_ABS_GEAR', 2, null, 20, 45);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_ABS_GEAR', 3, null, 40, 85);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_ABS_GEAR', 4, null, 75, 125);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_ABS_GEAR', 5, null, 115, 190);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_ABS_GEAR', 6, null, 175, 250);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_PERC_GEAR', 1, null, 5, 8);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_PERC_GEAR', 2, null, 7, 15);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_PERC_GEAR', 3, null, 13, 28);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_PERC_GEAR', 4, null, 23, 43);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_PERC_GEAR', 5, null, 32, 65);
insert into dynamic_property values (default, 'GEAR', 'STRENGTH_PERC_GEAR', 6, null, 53, 84);
insert into dynamic_property values (default, 'GEAR', 'CRIT_GEAR', 1, null, 8, 22);
insert into dynamic_property values (default, 'GEAR', 'CRIT_GEAR', 2, null, 18, 25);
insert into dynamic_property values (default, 'GEAR', 'CRIT_GEAR', 3, null, 21, 30);
insert into dynamic_property values (default, 'GEAR', 'CRIT_GEAR', 4, null, 25, 36);
insert into dynamic_property values (default, 'GEAR', 'CRIT_GEAR', 5, null, 32, 42);
insert into dynamic_property values (default, 'GEAR', 'CRIT_GEAR', 6, null, 37, 50);
insert into dynamic_property values (default, 'GEAR', 'CRIT_MULT_GEAR', 1, null, 5, 8);
insert into dynamic_property values (default, 'GEAR', 'CRIT_MULT_GEAR', 2, null, 7, 15);
insert into dynamic_property values (default, 'GEAR', 'CRIT_MULT_GEAR', 3, null, 13, 28);
insert into dynamic_property values (default, 'GEAR', 'CRIT_MULT_GEAR', 4, null, 23, 43);
insert into dynamic_property values (default, 'GEAR', 'CRIT_MULT_GEAR', 5, null, 32, 65);
insert into dynamic_property values (default, 'GEAR', 'CRIT_MULT_GEAR', 6, null, 53, 84);
insert into dynamic_property values (default, 'GEAR', 'INITIATIVE_GEAR', 1, null, 5, 17);
insert into dynamic_property values (default, 'GEAR', 'INITIATIVE_GEAR', 2, null, 10, 19);
insert into dynamic_property values (default, 'GEAR', 'INITIATIVE_GEAR', 3, null, 13, 22);
insert into dynamic_property values (default, 'GEAR', 'INITIATIVE_GEAR', 4, null, 18, 25);
insert into dynamic_property values (default, 'GEAR', 'INITIATIVE_GEAR', 5, null, 21, 29);
insert into dynamic_property values (default, 'GEAR', 'INITIATIVE_GEAR', 6, null, 25, 34);
insert into dynamic_property values (default, 'GEAR', 'SPEED_GEAR', 1, null, 5, 17);
insert into dynamic_property values (default, 'GEAR', 'SPEED_GEAR', 2, null, 10, 19);
insert into dynamic_property values (default, 'GEAR', 'SPEED_GEAR', 3, null, 13, 22);
insert into dynamic_property values (default, 'GEAR', 'SPEED_GEAR', 4, null, 18, 25);
insert into dynamic_property values (default, 'GEAR', 'SPEED_GEAR', 5, null, 21, 29);
insert into dynamic_property values (default, 'GEAR', 'SPEED_GEAR', 6, null, 25, 34);
insert into dynamic_property values (default, 'GEAR', 'RESISTANCE_GEAR', 1, null, 5, 8);
insert into dynamic_property values (default, 'GEAR', 'RESISTANCE_GEAR', 2, null, 7, 15);
insert into dynamic_property values (default, 'GEAR', 'RESISTANCE_GEAR', 3, null, 13, 28);
insert into dynamic_property values (default, 'GEAR', 'RESISTANCE_GEAR', 4, null, 23, 43);
insert into dynamic_property values (default, 'GEAR', 'RESISTANCE_GEAR', 5, null, 32, 65);
insert into dynamic_property values (default, 'GEAR', 'RESISTANCE_GEAR', 6, null, 53, 84);
insert into dynamic_property values (default, 'GEAR', 'DEXTERITY_GEAR', 1, null, 5, 8);
insert into dynamic_property values (default, 'GEAR', 'DEXTERITY_GEAR', 2, null, 7, 15);
insert into dynamic_property values (default, 'GEAR', 'DEXTERITY_GEAR', 3, null, 13, 28);
insert into dynamic_property values (default, 'GEAR', 'DEXTERITY_GEAR', 4, null, 23, 43);
insert into dynamic_property values (default, 'GEAR', 'DEXTERITY_GEAR', 5, null, 32, 65);
insert into dynamic_property values (default, 'GEAR', 'DEXTERITY_GEAR', 6, null, 53, 84);

insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 1, 'HP_ABS', 10);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 2, 'HP_ABS', 25);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 3, 'HP_ABS', 60);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 4, 'HP_ABS', 90);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 5, 'HP_ABS', 133);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 6, 'HP_ABS', 175);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 7, 'HP_ABS', 210);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 8, 'HP_ABS', 265);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 9, 'HP_ABS', 333);
insert into dynamic_property values (default, 'JEWEL', 'HP_ABS_JEWEL', 10, 'HP_ABS', 500);

insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 1, 'HP_PERC', 1);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 2, 'HP_PERC', 3);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 3, 'HP_PERC', 5);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 4, 'HP_PERC', 7);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 5, 'HP_PERC', 10);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 6, 'HP_PERC', 13);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 7, 'HP_PERC', 16);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 8, 'HP_PERC', 20);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 9, 'HP_PERC', 25);
insert into dynamic_property values (default, 'JEWEL', 'HP_PERC_JEWEL', 10, 'HP_PERC', 33);

insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 1, 'ARMOR_ABS', 10);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 2, 'ARMOR_ABS', 25);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 3, 'ARMOR_ABS', 60);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 4, 'ARMOR_ABS', 90);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 5, 'ARMOR_ABS', 133);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 6, 'ARMOR_ABS', 175);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 7, 'ARMOR_ABS', 210);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 8, 'ARMOR_ABS', 265);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 9, 'ARMOR_ABS', 333);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_ABS_JEWEL', 10, 'ARMOR_ABS', 500);

insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 1, 'ARMOR_PERC', 1);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 2, 'ARMOR_PERC', 3);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 3, 'ARMOR_PERC', 5);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 4, 'ARMOR_PERC', 7);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 5, 'ARMOR_PERC', 10);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 6, 'ARMOR_PERC', 13);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 7, 'ARMOR_PERC', 16);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 8, 'ARMOR_PERC', 20);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 9, 'ARMOR_PERC', 25);
insert into dynamic_property values (default, 'JEWEL', 'ARMOR_PERC_JEWEL', 10, 'ARMOR_PERC', 33);

insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 1, 'STRENGTH_ABS', 10);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 2, 'STRENGTH_ABS', 25);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 3, 'STRENGTH_ABS', 60);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 4, 'STRENGTH_ABS', 90);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 5, 'STRENGTH_ABS', 133);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 6, 'STRENGTH_ABS', 175);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 7, 'STRENGTH_ABS', 210);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 8, 'STRENGTH_ABS', 265);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 9, 'STRENGTH_ABS', 333);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_ABS_JEWEL', 10, 'STRENGTH_ABS', 500);

insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 1, 'STRENGTH_PERC', 1);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 2, 'STRENGTH_PERC', 3);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 3, 'STRENGTH_PERC', 5);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 4, 'STRENGTH_PERC', 7);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 5, 'STRENGTH_PERC', 10);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 6, 'STRENGTH_PERC', 13);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 7, 'STRENGTH_PERC', 16);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 8, 'STRENGTH_PERC', 20);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 9, 'STRENGTH_PERC', 25);
insert into dynamic_property values (default, 'JEWEL', 'STRENGTH_PERC_JEWEL', 10, 'STRENGTH_PERC', 33);

insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 1, 'CRIT', 1);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 2, 'CRIT', 2);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 3, 'CRIT', 3);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 4, 'CRIT', 4);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 5, 'CRIT', 5);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 6, 'CRIT', 6);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 7, 'CRIT', 7);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 8, 'CRIT', 8);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 9, 'CRIT', 9);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_JEWEL', 10, 'CRIT', 10);

insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 1, 'CRIT_MULT', 1);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 2, 'CRIT_MULT', 3);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 3, 'CRIT_MULT', 5);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 4, 'CRIT_MULT', 8);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 5, 'CRIT_MULT', 11);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 6, 'CRIT_MULT', 15);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 7, 'CRIT_MULT', 20);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 8, 'CRIT_MULT', 25);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 9, 'CRIT_MULT', 33);
insert into dynamic_property values (default, 'JEWEL', 'CRIT_MULT_JEWEL', 10, 'CRIT_MULT', 40);

insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 1, 'RESISTANCE', 1);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 2, 'RESISTANCE', 2);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 3, 'RESISTANCE', 3);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 4, 'RESISTANCE', 5);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 5, 'RESISTANCE', 7);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 6, 'RESISTANCE', 9);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 7, 'RESISTANCE', 12);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 8, 'RESISTANCE', 15);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 9, 'RESISTANCE', 19);
insert into dynamic_property values (default, 'JEWEL', 'RESISTANCE_JEWEL', 10, 'RESISTANCE', 25);

insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 1, 'DEXTERITY', 1);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 2, 'DEXTERITY', 2);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 3, 'DEXTERITY', 3);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 4, 'DEXTERITY', 5);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 5, 'DEXTERITY', 7);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 6, 'DEXTERITY', 9);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 7, 'DEXTERITY', 12);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 8, 'DEXTERITY', 15);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 9, 'DEXTERITY', 19);
insert into dynamic_property values (default, 'JEWEL', 'DEXTERITY_JEWEL', 10, 'DEXTERITY', 25);

insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 1, 'SPEED', 1);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 2, 'SPEED', 2);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 3, 'SPEED', 3);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 4, 'SPEED', 4);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 5, 'SPEED', 5);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 6, 'SPEED', 6);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 7, 'SPEED', 7);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 8, 'SPEED', 8);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 9, 'SPEED', 9);
insert into dynamic_property values (default, 'JEWEL', 'SPEED_JEWEL', 10, 'SPEED', 10);

insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 1, 'INITIATIVE', 1);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 2, 'INITIATIVE', 2);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 3, 'INITIATIVE', 3);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 4, 'INITIATIVE', 4);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 5, 'INITIATIVE', 5);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 6, 'INITIATIVE', 6);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 7, 'INITIATIVE', 7);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 8, 'INITIATIVE', 8);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 9, 'INITIATIVE', 9);
insert into dynamic_property values (default, 'JEWEL', 'INITIATIVE_JEWEL', 10, 'INITIATIVE', 10);

insert into dynamic_property values (default, 'SET', 'STONE_SKIN_SET', null, 'ARMOR_PERC', 25);
insert into dynamic_property values (default, 'SET', 'VITAL_AURA_SET', null, 'HP_PERC', 25);
insert into dynamic_property values (default, 'SET', 'POWER_FIST_SET', null, 'STRENGTH_PERC', 25);
