update dynamic_property set category = 'UPGRADE_TIME' where category = 'BUILDING_UP_TIME';
update dynamic_property set category = 'UPGRADE_COST' where category = 'BUILDING_UP_COST';

insert into dynamic_property (category, type, level, value1) values
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 2, 150), -- 2.5 m
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 3, 300), -- 5 m
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 4, 600), -- 10 m
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 5, 3600), -- 1 h
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 6, 10800), -- 3 h
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 7, 43200), -- 12 h
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 8, 86400), -- 24 h
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 9, 172800), -- 2 d
('UPGRADE_TIME', 'VEHICLE_0_UP_TIME', 10, 259200), -- 3 d

('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 2, 300), -- 5 m
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 3, 600), -- 10 m
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 4, 1200), -- 20 m
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 5, 7200), -- 2 h
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 6, 21600), -- 6 h
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 7, 86400), -- 24 h
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 8, 172800), -- 2 d
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 9, 345600), -- 4 d
('UPGRADE_TIME', 'VEHICLE_1_UP_TIME', 10, 518400), -- 6 d

('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 2, 450), -- 7.5 m
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 3, 900), -- 15 m
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 4, 1800), -- 30 m
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 5, 10800), -- 3 h
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 6, 32400), -- 9 h
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 7, 129600), -- 36 h
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 8, 172800), -- 3 d
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 9, 259200), -- 6 d
('UPGRADE_TIME', 'VEHICLE_2_UP_TIME', 10, 777600), -- 9 d

('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 2, 600), -- 10 m
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 3, 1200), -- 20 m
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 4, 2400), -- 40 m
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 5, 14400), -- 4 h
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 6, 43200), -- 12h
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 7, 172800), -- 48 h
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 8, 345600), -- 4 d
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 9, 691200), -- 8 d
('UPGRADE_TIME', 'VEHICLE_3_UP_TIME', 10, 1036800), -- 12 d

('UPGRADE_TIME', 'PART_BASIC_UP_TIME', 2, 600), -- 10 m
('UPGRADE_TIME', 'PART_BASIC_UP_TIME', 3, 1200), -- 20 m
('UPGRADE_TIME', 'PART_BASIC_UP_TIME', 4, 1800), -- 30 m
('UPGRADE_TIME', 'PART_BASIC_UP_TIME', 5, 3600), -- 1 h
('UPGRADE_TIME', 'PART_BASIC_UP_TIME', 6, 14400), -- 4h

('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 2, 600), -- 10 m
('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 3, 1200), -- 20 m
('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 4, 2400), -- 40 m
('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 5, 5400), -- 1.5 h
('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 6, 14400), -- 4h
('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 7, 28800), -- 8 h
('UPGRADE_TIME', 'PART_MODERATE_UP_TIME', 8, 43200), -- 12 h

('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 2, 600), -- 10 m
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 3, 1200), -- 20 m
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 4, 2400), -- 40 m
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 5, 7200), -- 2 h
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 6, 21600), -- 6h
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 7, 43200), -- 12 h
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 8, 86400), -- 24 h
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 9, 172800), -- 2 d
('UPGRADE_TIME', 'PART_GOOD_UP_TIME', 10, 259200); -- 3 d


insert into dynamic_property (category, type, level, resource_type, value1) values

('UPGRADE_COST', 'VEHICLE_0_UP_COST', 2, 'METAL', 10),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 3, 'METAL', 50),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 3, 'IRON', 5),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 4, 'METAL', 100),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 4, 'IRON', 15),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 5, 'METAL', 200),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 5, 'IRON', 30),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 5, 'STEAL', 5),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 6, 'METAL', 300),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 6, 'IRON', 50),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 6, 'STEAL', 10),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 7, 'METAL', 400),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 7, 'IRON', 100),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 7, 'STEAL', 25),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 8, 'METAL', 500),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 8, 'IRON', 150),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 8, 'STEAL', 50),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 9, 'METAL', 1000),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 9, 'IRON', 300),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 9, 'STEAL', 200),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 10, 'METAL', 2000),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 10, 'IRON', 750),
('UPGRADE_COST', 'VEHICLE_0_UP_COST', 10, 'STEAL', 500),

('UPGRADE_COST', 'VEHICLE_1_UP_COST', 2, 'METAL', 20),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 3, 'METAL', 100),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 3, 'IRON', 10),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 4, 'METAL', 200),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 4, 'IRON', 30),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 5, 'METAL', 400),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 5, 'IRON', 60),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 5, 'STEAL', 10),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 6, 'METAL', 600),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 6, 'IRON', 100),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 6, 'STEAL', 20),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 7, 'METAL', 800),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 7, 'IRON', 200),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 7, 'STEAL', 50),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 8, 'METAL', 1000),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 8, 'IRON', 300),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 8, 'STEAL', 100),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 9, 'METAL', 2000),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 9, 'IRON', 600),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 9, 'STEAL', 400),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 10, 'METAL', 4000),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 10, 'IRON', 1500),
('UPGRADE_COST', 'VEHICLE_1_UP_COST', 10, 'STEAL', 1000),

('UPGRADE_COST', 'VEHICLE_2_UP_COST', 2, 'METAL', 30),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 3, 'METAL', 150),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 3, 'IRON', 15),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 4, 'METAL', 300),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 4, 'IRON', 45),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 5, 'METAL', 600),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 5, 'IRON', 90),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 5, 'STEAL', 15),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 6, 'METAL', 450),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 6, 'IRON', 150),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 6, 'STEAL', 30),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 7, 'METAL', 1200),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 7, 'IRON', 300),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 7, 'STEAL', 75),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 8, 'METAL', 1500),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 8, 'IRON', 450),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 8, 'STEAL', 150),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 9, 'METAL', 3000),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 9, 'IRON', 900),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 9, 'STEAL', 600),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 10, 'METAL', 6000),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 10, 'IRON', 2250),
('UPGRADE_COST', 'VEHICLE_2_UP_COST', 10, 'STEAL', 1500),

('UPGRADE_COST', 'VEHICLE_3_UP_COST', 2, 'METAL', 40),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 3, 'METAL', 200),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 3, 'IRON', 20),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 4, 'METAL', 400),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 4, 'IRON', 60),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 5, 'METAL', 800),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 5, 'IRON', 120),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 5, 'STEAL', 20),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 6, 'METAL', 1200),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 6, 'IRON', 200),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 6, 'STEAL', 40),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 7, 'METAL', 1600),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 7, 'IRON', 400),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 7, 'STEAL', 100),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 8, 'METAL', 2000),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 8, 'IRON', 600),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 8, 'STEAL', 200),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 9, 'METAL', 4000),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 9, 'IRON', 1200),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 9, 'STEAL', 800),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 10, 'METAL', 8000),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 10, 'IRON', 3000),
('UPGRADE_COST', 'VEHICLE_3_UP_COST', 10, 'STEAL', 2000),

('UPGRADE_COST', 'PART_BASIC_UP_COST', 2, 'METAL', 10),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 3, 'METAL', 30),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 3, 'IRON', 5),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 4, 'METAL', 50),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 4, 'IRON', 30),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 5, 'METAL', 150),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 5, 'IRON', 50),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 5, 'STEAL', 5),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 6, 'METAL', 500),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 6, 'IRON', 150),
('UPGRADE_COST', 'PART_BASIC_UP_COST', 6, 'STEAL', 25),

('UPGRADE_COST', 'PART_MODERATE_UP_COST', 2, 'METAL', 10),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 3, 'METAL', 30),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 3, 'IRON', 5),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 4, 'METAL', 50),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 4, 'IRON', 30),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 5, 'METAL', 150),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 5, 'IRON', 50),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 5, 'STEAL', 5),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 6, 'METAL', 500),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 6, 'IRON', 150),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 6, 'STEAL', 25),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 7, 'METAL', 750),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 7, 'IRON', 250),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 7, 'STEAL', 100),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 8, 'METAL', 1500),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 8, 'IRON', 500),
('UPGRADE_COST', 'PART_MODERATE_UP_COST', 8, 'STEAL', 250),

('UPGRADE_COST', 'PART_GOOD_UP_COST', 2, 'METAL', 10),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 3, 'METAL', 30),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 3, 'IRON', 5),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 4, 'METAL', 50),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 4, 'IRON', 30),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 5, 'METAL', 150),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 5, 'IRON', 50),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 5, 'STEAL', 5),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 6, 'METAL', 500),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 6, 'IRON', 150),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 6, 'STEAL', 25),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 7, 'METAL', 750),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 7, 'IRON', 250),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 7, 'STEAL', 100),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 8, 'METAL', 1500),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 8, 'IRON', 500),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 8, 'STEAL', 250),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 9, 'METAL', 2000),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 9, 'IRON', 750),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 9, 'STEAL', 350),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 10, 'METAL', 2500),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 10, 'IRON', 1000),
('UPGRADE_COST', 'PART_GOOD_UP_COST', 10, 'STEAL', 500);
