alter table progress drop column if exists vehicle_storage;
alter table progress drop column if exists vehicle_part_storage;
alter table progress add column if not exists vehicle_upgrade_level int not null default 0;

alter table dynamic_property add column if not exists progress_stat varchar(32);

delete from dynamic_property where type = 'GARAGE_BUILDING';
insert into dynamic_property (category, type, level, progress_stat, value1) values
('BUILDING', 'GARAGE_BUILDING', 1, 'VEHICLE_UPGRADE_LEVEL', 2),
('BUILDING', 'GARAGE_BUILDING', 2, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 3, 'GARAGE_SLOT', 1),
('BUILDING', 'GARAGE_BUILDING', 4, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 5, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 5, 'MISSION_MAX_BATTLES', 1),
('BUILDING', 'GARAGE_BUILDING', 6, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 7, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 7, 'BUILDER_QUEUE', 1),
('BUILDING', 'GARAGE_BUILDING', 8, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 9, 'VEHICLE_UPGRADE_LEVEL', 1),
('BUILDING', 'GARAGE_BUILDING', 10, 'MISSION_MAX_BATTLES', 1),
('BUILDING', 'GARAGE_BUILDING', 10, 'VEHICLE_UPGRADE_LEVEL', 1);

delete from dynamic_property where type = 'ACADEMY_BUILDING';
insert into dynamic_property (category, type, level, progress_stat, value1) values
('BUILDING', 'ACADEMY_BUILDING', 1, 'HERO_TRAIN_LEVEL', 10),
('BUILDING', 'ACADEMY_BUILDING', 2, 'HERO_TRAIN_LEVEL', 10),
('BUILDING', 'ACADEMY_BUILDING', 3, 'HERO_TRAIN_LEVEL', 10),
('BUILDING', 'ACADEMY_BUILDING', 4, 'HERO_TRAIN_LEVEL', 10),
('BUILDING', 'ACADEMY_BUILDING', 5, 'HERO_TRAIN_LEVEL', 10),
('BUILDING', 'ACADEMY_BUILDING', 6, 'HERO_TRAIN_LEVEL', 10);

delete from dynamic_property where type = 'JEWELRY_BUILDING';
insert into dynamic_property (category, type, level, progress_stat, value1) values
('BUILDING', 'JEWELRY_BUILDING', 1, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 2, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 3, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 4, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 5, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 6, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 7, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 8, 'JEWEL_UPGRADE_LEVEL', 1),
('BUILDING', 'JEWELRY_BUILDING', 9, 'JEWEL_UPGRADE_LEVEL', 1);

delete from dynamic_property where type in ('FORGE_BUILDING', 'FORGE_MOD_RARITY', 'FORGE_MOD_SPEED', 'FORGE_BREAKDOWN_RARITY', 'FORGE_BREAKDOWN_RES', 'FORGE_REROLL_QUAL', 'FORGE_REROLL_STAT', 'FORGE_INC_RARITY', 'FORGE_REROLL_JEWEL', 'FORGE_ADD_JEWEL', 'FORGE_ADD_SP_JEWEL');
insert into dynamic_property (category, type, level, progress_stat, value1) values
('BUILDING', 'FORGE_BUILDING', 1, 'GEAR_MOD_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 2, 'GEAR_MOD_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 4, 'GEAR_MOD_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 6, 'GEAR_MOD_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 8, 'GEAR_MOD_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 10, 'GEAR_MOD_RARITY', 1),

('BUILDING', 'FORGE_BUILDING', 3, 'GEAR_MOD_SPEED', 20),
('BUILDING', 'FORGE_BUILDING', 5, 'GEAR_MOD_SPEED', 20),
('BUILDING', 'FORGE_BUILDING', 7, 'GEAR_MOD_SPEED', 20),
('BUILDING', 'FORGE_BUILDING', 9, 'GEAR_MOD_SPEED', 20),
('BUILDING', 'FORGE_BUILDING', 10, 'GEAR_MOD_SPEED', 20),

('BUILDING', 'FORGE_BUILDING', 1, 'GEAR_BREAKDOWN_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 2, 'GEAR_BREAKDOWN_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 3, 'GEAR_BREAKDOWN_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 4, 'GEAR_BREAKDOWN_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 5, 'GEAR_BREAKDOWN_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 6, 'GEAR_BREAKDOWN_RARITY', 1),

('BUILDING', 'FORGE_BUILDING', 2, 'GEAR_BREAKDOWN_RESOURCES', 10),
('BUILDING', 'FORGE_BUILDING', 4, 'GEAR_BREAKDOWN_RESOURCES', 10),
('BUILDING', 'FORGE_BUILDING', 6, 'GEAR_BREAKDOWN_RESOURCES', 10),
('BUILDING', 'FORGE_BUILDING', 8, 'GEAR_BREAKDOWN_RESOURCES', 10),
('BUILDING', 'FORGE_BUILDING', 10, 'GEAR_BREAKDOWN_RESOURCES', 10),

('BUILDING', 'FORGE_BUILDING', 1, 'REROLL_GEAR_QUALITY', 1),
('BUILDING', 'FORGE_BUILDING', 3, 'REROLL_GEAR_STAT', 1),
('BUILDING', 'FORGE_BUILDING', 7, 'INC_GEAR_RARITY', 1),
('BUILDING', 'FORGE_BUILDING', 8, 'REROLL_GEAR_JEWEL', 1),
('BUILDING', 'FORGE_BUILDING', 9, 'ADD_GEAR_JEWEL', 1),
('BUILDING', 'FORGE_BUILDING', 10, 'ADD_GEAR_SPECIAL_JEWEL', 1);

update dynamic_property set progress_stat = 'BARRACKS_SIZE' where type = 'BARRACKS_BUILDING';

delete from dynamic_property where type in ('LABORATORY_BUILDING', 'LABORATORY_INCUBATORS', 'LABORATORY_SPEED');
insert into dynamic_property (category, type, level, progress_stat, value1) values
('BUILDING', 'LABORATORY_BUILDING', 1, 'INCUBATORS', 1),
('BUILDING', 'LABORATORY_BUILDING', 3, 'INCUBATORS', 1),
('BUILDING', 'LABORATORY_BUILDING', 5, 'INCUBATORS', 1),
('BUILDING', 'LABORATORY_BUILDING', 7, 'INCUBATORS', 1),
('BUILDING', 'LABORATORY_BUILDING', 9, 'INCUBATORS', 1),

('BUILDING', 'LABORATORY_BUILDING', 2, 'LAB_SPEED', 20),
('BUILDING', 'LABORATORY_BUILDING', 4, 'LAB_SPEED', 20),
('BUILDING', 'LABORATORY_BUILDING', 6, 'LAB_SPEED', 20),
('BUILDING', 'LABORATORY_BUILDING', 8, 'LAB_SPEED', 20),
('BUILDING', 'LABORATORY_BUILDING', 10, 'LAB_SPEED', 20);
