package io.pacworx.ambrosia.story

enum class StoryTrigger {
    PLAYER_NEW,
    PLAYER_COLOR_SELECTED,
    BARRACKS_ENTERED,
    ACADEMY_DISCOVERED,
    ACADEMY_ENTERED,
    LABORATORY_DISCOVERED,
    LABORATORY_ENTERED,
    ARENA_DISCOVERED,
    ARENA_ENTERED,
    GARAGE_DISCOVERED,
    GARAGE_ENTERED,
    JEWELRY_DISCOVERED,
    JEWELRY_ENTERED,
    STORAGE_ENTERED,
    FORGE_DISCOVERED,
    FORGE_ENTERED,
    VEHICLE_FOUND,
    GENOMES_FOUND
}
